version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: dependabot-updates
  ignore:
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.1
  - dependency-name: babel-preset-gatsby
    versions:
    - 0.11.0
    - 0.12.1
    - 0.12.2
    - 1.2.0
  - dependency-name: react-instantsearch-dom
    versions:
    - 6.10.0
    - 6.8.3
    - 6.9.0
  - dependency-name: styled-icons
    versions:
    - 10.27.0
    - 10.28.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.11.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.4
    - 2.14.1
  - dependency-name: "@react95/core"
    versions:
    - 3.0.4
